name: Checkbox Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      trigger-code:
        description: 'Execute in Jira'
        required: true
        default: false

jobs:
  run-if-checked:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create env file
        run: |
          touch .env
          echo "XRAY_API_BASE_URL=https://xray.cloud.getxray.app" >> .env
          echo "XRAY_EXECUTION_TEST_ENVIRONMENTS=QA" >> .env
          echo "XRAY_EXECUTION_SUMMARY=Smoke tests" >> .env
          echo "XRAY_CLIENT_ID=${{ secrets.XRAY_CLIENT_ID }}" >> .env
          echo "XRAY_CLIENT_SECRET=${{ secrets.XRAY_CLIENT_SECRET }}" >> .env
          cat .env

      - name: Run if checkbox is checked
        if: ${{ github.event.inputs.trigger-code == 'true' }}
        run: pytest --jira-xray --cloud --client-secret-auth

  run-if-not-checked:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create env file
        run: |
          touch .env
          echo "XRAY_API_BASE_URL=https://xray.cloud.getxray.app" >> .env
          echo "XRAY_EXECUTION_TEST_ENVIRONMENTS=QA" >> .env
          echo "XRAY_EXECUTION_SUMMARY=Smoke tests" >> .env
          echo "XRAY_CLIENT_ID=${{ secrets.XRAY_CLIENT_ID }}" >> .env
          echo "XRAY_CLIENT_SECRET=${{ secrets.XRAY_CLIENT_SECRET }}" >> .env
          cat .env

      - name: Run if checkbox is not checked
        if: ${{ github.event.inputs.trigger-code == 'false' }}
        run: pytest --jira-xray --cloud --client-secret-auth
